services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    env_file:
      - .env