"""Fixed Auto Increment error

Revision ID: 7b78133c1eb4
Revises: 
Create Date: 2026-04-03 06:35:03.165419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b78133c1eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('row_id', sa.String(length=36), nullable=True),
    sa.Column('changed_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('DONOR', 'NGO', 'DELIVERY_PARTNER', 'ADMIN'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('delivery_partners',
    sa.Column('dp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('fullname', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('vehicle_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('dp_id')
    )
    op.create_table('food_listings',
    sa.Column('fid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('food_type', sa.Enum('prepared', 'raw', 'packaged', 'baked'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('quantity_unit', sa.Enum('kg', 'g', 'units', 'liters'), nullable=False),
    sa.Column('preparation_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'MATCHED', 'PICKED_UP', 'DELIVERED', 'EXPIRED'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_table('ngos',
    sa.Column('ngo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('current_capacity', sa.Integer(), nullable=True),
    sa.Column('food_preferences', sa.JSON(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('ngo_id')
    )
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dp_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('time_taken', sa.String(length=50), nullable=True),
    sa.Column('location_pickup', sa.Text(), nullable=True),
    sa.Column('location_drop', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['dp_id'], ['delivery_partners.dp_id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food_listings.fid'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.ngo_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('ngos')
    op.drop_table('food_listings')
    op.drop_table('delivery_partners')
    op.drop_table('users')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
